config/routes.rb
Rails.application.routes.draw do
	root :to => "home#index"
  resources :users do
  	collection do
	    get 'get_role_users'
	  end 
  end
  resources :roles do
  	collection do
	    get 'hide_roles'
	    post 'update_roles'
	    get 'get_role_users'
	  end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :user_roles
  has_many :users, through: :user_roles
  validates :name, presence: true, uniqueness: {case_sensitive: false}
end

app/models/user.rb
class User < ApplicationRecord
	has_many :user_roles, dependent: :destroy
  has_many :roles, through: :user_roles
  has_many_attached :images
  has_many :user_meta_data
  accepts_nested_attributes_for :user_meta_data, allow_destroy: true
  validates :email, presence: true, uniqueness: {case_sensitive: false}
  accepts_nested_attributes_for :roles

  def user_meta_datum_record key
	   user_meta_data.detect { |ele| ele.meta_key == key }
	end

	def user_meta_datum(*args)
   meta_key, meta_value = args
   meta_key = meta_key && meta_key.to_s
   	if args.size == 1
      p = user_meta_datum_record(meta_key) && p.meta_value
   	elsif args.size == 2
      raise ArgumentError, "invalid key #{meta_key.inspect}" unless meta_key
      # Find or create a custom field object with the appropriate key
      p = user_meta_datum_record(meta_key) || self.user_meta_data.new(meta_key: meta_key)
      p.value = value
   	else raise ArgumentError, "wrong number of arguments (#{args.size} for 1 or 2)"
  	end
	end
end

app/models/user_meta_datum.rb
class UserMetaDatum < ApplicationRecord
	belongs_to :user
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  def index
    @roles = Role.all
  end

  def show
  end

  def new
    @role = Role.new
  end

  def edit
  end

  
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  def hide_roles
    @roles = Role.all
  end

  def update_roles
    Role.update(params[:role].keys, params[:role].values)
    flash[:notice] = "Updated roles"
    redirect_to roles_path
  end

  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name, :hide_status, {})
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :get_roles, only: [:new, :edit, :update, :index, :create]

  def index
    #@users_grid = initialize_grid(User.all)
    @users = User.includes(:roles).all
  end

  def get_role_users
    @users = User.includes(:roles).all
    if params[:role_id].present?
      @users = @users.references(:roles).where("roles.id = ?", params[:role_id])
    end
    respond_to do |format|
      format.js
    end
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        @user.images.attach(params[:user][:images]) if params[:user][:images].present?
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }

      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        @user.images.attach(params[:user][:images]) if params[:user][:images].present?
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, role_ids: [], images: [], user_meta_data_attributes: {})
    end

    def get_roles
      @roles = Role.where(hide_status: false)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def tag_options(options, escape = true)
	    tag_builder.tag_options(options, escape)
	  end
end

app/views/home/index.html.erb
<h1>User Management</h1>
<h2> <%= link_to "Manage Roles", roles_path %> </h2>
<h2> <%= link_to "Manage Users", users_path %> </h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserManagement</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/roles/_form.html.erb
<%= form_with(model: role, local: true) do |form| %>
  <% if role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :role_name %>
  </div>

  <div class="field">
    <%= form.label :hide_status %>
    <%= form.check_box :hide_status, id: :role_hide_status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/hide_roles.html.erb
<h3> Hide Roles <h3/>
<%= form_for :role, :url => {:action => 'update_roles'} do -%>
    <% @roles.each do |role| %>
      <%= fields_for "role[]", role do |role_fields| %>
        <%= role_fields.check_box :hide_status %>
        <%= role.name %>
      <% end %>
    <% end %>
    <%= submit_tag 'Update' %>
<% end %>
<%= link_to 'Backe to roles', roles_path %>

app/views/roles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Roles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Hide status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.name %></td>
        <td><%= role.hide_status %></td>
        <td><%= link_to 'Show', role %></td>
        <td><%= link_to 'Edit', edit_role_path(role) %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role', new_role_path %>
<%= link_to 'Hide Roles', hide_roles_roles_path %>
<%= link_to 'Home', root_path %>

app/views/roles/new.html.erb
<h1>New Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @role.name %>
</p>

<p>
  <strong>Hide status:</strong>
  <%= @role.hide_status %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>

app/views/users/_form.html.erb
<%= bootstrap_form_for(user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :first_name, id: :user_first_name %>
  </div>

  <div class="field">
    <%= form.text_field :last_name, id: :user_last_name %>
  </div>

  <div class="field">
    <%= form.text_field :email, id: :user_email %>
  </div>
  <%= form.collection_select :role_ids, @roles, :id, :name, {}, :multiple => 'true'%>
  <% if form.object.images.present? %>
    <% form.object.images.each do |image| %>
    <%= image_tag(image, size: "100x100", alt: "Edit Entry") %>
    <% end %>
  <% end %>
  <%= form.file_field :images, multiple: true %>

  <%= form.nested_fields_for :user_meta_data do |f| %>
    <%= f.remove_nested_fields_link %>
    <%= f.text_field :meta_key, label: 'Column Name', placeholder: 'Add column' %>
    <%= f.text_field :meta_value, label: 'Column Value', placeholder: 'Add Value' %>
  <% end %>
  <%= form.add_nested_fields_link :user_meta_data %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_index.html.erb
<table>
  <thead>
    <tr>
      <th>Images</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>User Roles</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
        <td>
          <% if user.images.present? %>
            <% user.images.each do |image| %>
            <%= image_tag(image, size: "100x100", alt: "Edit Entry") %>
            <% end %>
          <% end %>
        </td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.roles.pluck(:name).to_sentence %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/get_role_users.js.erb
$(".users-grid").html("<%= escape_javascript(render 'index', users: @users) %>");

app/views/users/index.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "users.js" %>
<% end %>
<p id="notice"><%= notice %></p>

<h1>Users</h1>
<%= select_tag "roles", options_from_collection_for_select(@roles, "id", "name"), include_blank: "All" %>
<div class = 'users-grid'>
  <%= render 'index', users: @users %>
</div>

<%= link_to 'New User', new_user_path %>
<%= link_to 'Home', root_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<p>
  <strong>images</strong>
  <% if @user.images.present? %>
    <% @user.images.each do |image| %>
    <%= image_tag(image, size: "500x500", alt: "Edit Entry") %>
    <% end %>
  <% end %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>